const mapel = [
    "Pemrograman Web dan perangkat bergerak",
    "Pendidikan Agama Islam",
    "Pendidikan Kewarganegaraan",
    "Sejarah Indonesia",
    "Bahasa Indonesia",
    "Seni Budaya",
    "Pendidikan jasmani dan olahraga",
    "Matematika",
    "Bahasa Inggris",
    "Produk kreatif dan Kewirausahaan",
    "Fisika",
    "IPA",
    "Pengetahuan Bahan Makanan",
    "Boga dasar",
    "Tata hidang",
    "Pengolahan dan penyajian makanan",
    "Produk pastry dan bakery",
    "Produk kue dan cake Indonesia",
    "Keamanan pangan",
    "Ilmu Gizi",
    "Kepariwisataan",
    "Pemodelan perangkat lunak",
    "Pemrograman berorientasi objek",
    "Simulasi dan Komunikasi digital",
    "Basis Data",
    "Komputer dan Jaringan Dasar",
    "Kimia",
    "Matematika",
    "Pemrograman dasar",
    "Sistem Komputer",
    "Dasar desain grafis",
    "Bahasa Jawa",
]

export default mapel